### ISSUE TITLE
undefined is not a function error.

### ISSUE THREAD

**Issue by nayefc** [dustmoo/gridster.js#40]
Whatever I do, I keep getting this error when using gridster:

```undefined is not a function```

I've even copied exact full code samples from websites and try to run them and I still get the same error. Is this a known bug with latest on master?

**Comment by Ryan-Anderson** [comment]
Is your object a jQuery object? You are probably passing the dom element, and not the jquery object.

For example, if you have an element variable called 'element':

$(element).gridster();

Hopefully that fixes it.
